frase = input('Digite seu nome completo: ').strip()
print('Nome em maiúsculas: {}'.format(frase.upper()))
print('Nome em minúsculas: {}'.format(frase.lower()))
espaco = frase.count(' ')
print("Letras ao todo sem considerar espaços: {}".format(len(frase) - espaco))
divisao = frase.split()
print('Quantidade de letras do primeiro nome: {}'.format(len(divisao[0])))
print()
# ----------------------------------------------------------------------------------------
frase = input('Digite seu nome completo: ').strip()
print('Nome em maiúsculas: {}'.format(frase.upper()))
print('Nome em minúsculas: {}'.format(frase.lower()))
print('Letras ao todo sem considerar espaços: {}'.format(len(frase) - frase.count(' ')))
print('Quantidade de letras do primeiro nome: {}'.format(frase.find(' ')))